# Changes here will be overwritten by Copier

_commit: 0.1.53
_src_path: git@bbpgitlab.epfl.ch:neuromath/python-template.git
author_email: ''
author_name: Blue Brain Project, EPFL
copyright_license: Apache License 2.0
copyright_year: '2023'
distribution_name: dir-content-diff
download_url: https://github.com/BlueBrain/dir-content-diff
init_git: false
maintainer: Adrien Berchet (@adrien-berchet)
package_name: dir_content_diff
project_description: Simple tool to compare directory contents.
project_name: Directory Content Difference
project_url: https://dir-content-diff.readthedocs.io
repository_name: dir-content-diff
repository_namespace: BlueBrain
repository_provider: github
setup_codeql: false
ssh_url: git@github.com:BlueBrain/dir-content-diff.git
team_name: ''
tracker_url: https://github.com/BlueBrain/dir-content-diff/issues
use_pyproject_toml: false
version: 1.1.0

# End of Copier answers
