# Changes here will be overwritten by Copier

_commit: 0.1.7
_src_path: git@bbpgitlab.epfl.ch:neuromath/python-template.git
author_email: ''
author_name: Blue Brain Project, EPFL
copyright_license: Apache License 2.0
copyright_year: '2022'
download_url: git@github.com:BlueBrain/dir-content-diff.git
init_git: false
maintainer: Adrien Berchet (@adrien-berchet)
package_name: dir_content_diff
project_description: Simple tool to compare directory contents.
project_name: dir-content-diff
project_url: https://dir-content-diff.readthedocs.io
repository: BlueBrain/dir-content-diff
repository_provider: github
support_py37: false
team_name: ''
today: 29 August 2022
tracker_url: https://github.com/BlueBrain/dir-content-diff/issues
version: 1.1.0

# End of Copier answers
